#!/usr/bin/env python3
"""Regenerate the plan tables in Support/worklog/BRM-Plan-todo.md from the plans themselves.

The master index carries one row per plan: what it owns, how many items are done, how many are
still pending, and a status. Those numbers used to be copied by hand, which is why they were
wrong — the Build tab read 146/146 in the index while the file itself held 163 items.

This script is the mechanism that stops that. It counts the checkboxes in every
`Support/worklog/Plan-*.md`, groups the plans by area in a fixed order, and rewrites only the
region between the generated markers in the index. Everything outside those markers — the prose,
the routing tables, the retired-file map, the conventions — is written by hand and never touched.

Usage:
    python3 Support/build-release/scripts/update-plan-index.py           # rewrite the index
    python3 Support/build-release/scripts/update-plan-index.py --check   # fail if it is stale

`--check` is what CI runs: it never writes, and exits 1 when a plan's counts have moved without
the index following.

Counting rules:
    - `- [x]` is done, `- [ ]` is pending.
    - The Preferences plan also uses `- X`/`- V` (done) and `- D`/`- P` (not done) markers, which
      predate the checkbox convention. `D` means the UI exists but the behaviour does not, so it
      counts as pending — a half-wired setting is not a delivered one.
    - An index file with no items of its own (Plan-MainPanel) reports as a pointer, not as 0/0.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
WORKLOG = REPO_ROOT / "Support" / "worklog"
INDEX = WORKLOG / "BRM-Plan-todo.md"

START = "<!-- plan-index:start — generated by Support/build-release/scripts/update-plan-index.py -->"
END = "<!-- plan-index:end -->"

# Area -> ordered plans. The order is the reading order of the app itself: the window from the
# outside in, then the tabs left to right, then the work that is not a surface.
AREAS: list[tuple[str, str, list[tuple[str, str]]]] = [
    (
        "The window, by region",
        "The app is four regions. Each owns its own plan, so a change has exactly one home.",
        [
            ("Plan-AppShellUI-todo.md", "Whole window — background, material and glass language, theme and accent"),
            ("Plan-LeftSidebar-todo.md", "Left sidebar — repositories, recents, add/remove, the footer buttons"),
            ("Plan-MainPanel-todo.md", "Main panel — index over the three bands and six tabs below"),
            ("Plan-DetailViewPanel-todo.md", "Detail View panel — the right inspector and its cards"),
            ("Plan-StatusBar-todo.md", "Status bar — repository, branch, platform, auto-detect chips"),
        ],
    ),
    (
        "Inside the main panel",
        "The centre column is three stacked bands, each with its own plan.",
        [
            ("Plan-MainPanel-Header-todo.md", "Header — repository name, badge, path lines, Reveal / Terminal / Copy"),
            ("Plan-MainPanel-Toolbar-todo.md", "Toolbar — the six-tab picker and the rule beneath it"),
            ("Plan-MainPanel-Container-todo.md", "Container — work-area surface, padding, scrolling, card treatment"),
        ],
    ),
    (
        "The six tabs, inside the container",
        "Everything a tab *does* belongs to its own plan, not to the container.",
        [
            ("Plan-Tab-Build-todo.md", "Build — script discovery, the table, parameters, execution, live output"),
            ("Plan-Tab-Logs-todo.md", "Logs — saved log files, filters, search, export"),
            ("Plan-Tab-History-todo.md", "History — every recorded run for the repository"),
            ("Plan-Tab-Overview-todo.md", "Overview — repository summary and build statistics"),
            ("Plan-MarkdownExplorer-todo.md", "Docs — markdown discovery, rendering, Preview/Source editing"),
            ("Plan-Tab-Settings-todo.md", "Settings — per-repository, distinct from the Preferences window"),
        ],
    ),
    (
        "Features",
        "Product behaviour that spans regions rather than living in one of them.",
        [
            ("Plan-PreferenceScreen-todo.md", "Preferences window — seven tabs, every field, and the wiring audit"),
            ("Plan-Updates-todo.md", "Update checking — GitHub Releases feed, version comparison, channels"),
            ("Plan-Localization-todo.md", "Localization — English and Hindi, the string catalogue, switching"),
            ("Plan-WindowLayout-todo.md", "Window layout — resizing, the View menu, panel visibility"),
        ],
    ),
    (
        "Engineering, quality, and release",
        "Work that has no visible surface of its own, but decides whether the visible ones hold up.",
        [
            ("Plan-CodeRefactoring-Reusability-todo.md", "Feature extraction, dependency seams, reuse — behaviour preserving"),
            ("Plan-XcodeProject-todo.md", "Target membership, build settings, schemes, project-file hygiene"),
            ("Plan-QualityVerification-todo.md", "Non-functional targets, tests, GUI coverage, the evidence ledger"),
            ("Plan-ReleasePackaging-todo.md", "Release script, staging, the `.dmg`, tags, signing, publication"),
            ("Plan-ContextArchitectureVisuals-todo.md", "The SVG diagram set and its documentation wiring"),
        ],
    ),
]

DONE = re.compile(r"^\s*(?:- \[x\]|- [XV] )", re.IGNORECASE)
PENDING = re.compile(r"^\s*(?:- \[ \]|- [DP] )")


def count(path: Path) -> tuple[int, int]:
    """Return (done, pending) for one plan."""
    done = pending = 0
    for line in path.read_text(encoding="utf-8").splitlines():
        if DONE.match(line):
            done += 1
        elif PENDING.match(line):
            pending += 1
    return done, pending


def status_for(done: int, pending: int) -> str:
    if done + pending == 0:
        return "Index only"
    if pending == 0:
        return "Done ✅"
    if done == 0:
        return "Open"
    return "In progress"


def render() -> str:
    lines: list[str] = [START, ""]
    grand_done = grand_pending = 0
    area_totals: list[tuple[str, int, int]] = []

    body: list[str] = []
    for title, blurb, plans in AREAS:
        body += [f"### {title}", "", blurb, ""]
        body += ["| Plan | What it owns | Done | Pending | Status |", "| --- | --- | ---: | ---: | --- |"]
        area_done = area_pending = 0
        for filename, owns in plans:
            path = WORKLOG / filename
            if not path.exists():
                body.append(f"| `{filename}` | **MISSING FROM DISK** | — | — | Broken link |")
                continue
            done, pending = count(path)
            area_done += done
            area_pending += pending
            total = done + pending
            done_cell = f"{done}" if total else "—"
            pending_cell = f"{pending}" if total else "—"
            label = filename.removesuffix(".md")
            body.append(f"| [{label}]({filename}) | {owns} | {done_cell} | {pending_cell} | {status_for(done, pending)} |")
        body.append(
            f"| **{title} — subtotal** | | **{area_done}** | **{area_pending}** | "
            f"**{status_for(area_done, area_pending)}** |"
        )
        body.append("")
        area_totals.append((title, area_done, area_pending))
        grand_done += area_done
        grand_pending += area_pending

    grand_total = grand_done + grand_pending
    percent = round(grand_done / grand_total * 100) if grand_total else 0

    lines += [
        "## Where the work stands",
        "",
        f"**{grand_done} of {grand_total} items done — {grand_pending} still pending ({percent}%).**",
        "",
        "| Area | Done | Pending | Status |",
        "| --- | ---: | ---: | --- |",
    ]
    for title, done, pending in area_totals:
        lines.append(f"| {title} | {done} | {pending} | {status_for(done, pending)} |")
    lines.append(f"| **All areas** | **{grand_done}** | **{grand_pending}** | **{status_for(grand_done, grand_pending)}** |")
    lines += ["", "## The plans, by area", ""]
    lines += body
    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    check = "--check" in sys.argv
    text = INDEX.read_text(encoding="utf-8")
    if START not in text or END not in text:
        print(f"error: {INDEX} is missing the generated-region markers", file=sys.stderr)
        return 2

    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    updated = head + render() + tail

    if updated == text:
        print("Plan index is up to date.")
        return 0
    if check:
        print("Plan index is stale — run: python3 Support/build-release/scripts/update-plan-index.py", file=sys.stderr)
        return 1
    INDEX.write_text(updated, encoding="utf-8")
    print(f"Updated {INDEX.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
